fix: handle missing 'sites' and 'orgs' in enabled/disabled configuraions safely (#424)
Currently, some audit data in the database has an incomplete structure.
For example, broken-internal-links:
```
"broken-backlinks-internal": {
      "enabledByDefault": true,
      "disabled": {
        "sites": [
          "site-id",
        ],
        // missed orgs
      },
    },
```

The absence of the "orgs/sites" key leads to an error in

https://github.com/adobe/spacecat-shared/blob/main/packages/spacecat-shared-data-access/src/models/configuration.js#L39-L45

https://spacecat.coralogix.com/#/query-new/logs?id=qzf80Nda2AaKpjA4VSTle&page=0
```
TypeError: Cannot read properties of undefined (reading 'includes')
at Configuration.self.isHandlerEnabledForSite (/var/task/index.js:8360:77)
```

This PR includes the corrected logic to handle such cases.

Please ensure your pull request adheres to the following guidelines:
- [ ] make sure to link the related issues in this description
- [ ] when merging / squashing, make sure the fixed issue references are
visible in the commits, for easy compilation of release notes

## Related Issues


Thanks for contributing!