test: fix base model updatedAt test (#119)
In some cases, the test failed with assertion error, because it compared
expected with passed `updatedAt` on a new record (no id), whereas for
new records an `updatedAt` is generated in the constructor.

```
AssertionError: expected '2024-01-18T16:23:59.276Z' to equal '2024-01-18T16:23:59.275Z'
```