fix(deps): update external fixes (#569)
This PR contains the following updates:

| Package | Change | Age | Adoption | Passing | Confidence |
|---|---|---|---|---|---|
|
[@aws-sdk/client-dynamodb](https://redirect.github.com/aws/aws-sdk-js-v3/tree/main/clients/client-dynamodb)
([source](https://redirect.github.com/aws/aws-sdk-js-v3/tree/HEAD/clients/client-dynamodb))
| [`3.734.0` ->
`3.738.0`](https://renovatebot.com/diffs/npm/@aws-sdk%2fclient-dynamodb/3.734.0/3.738.0)
|
[![age](https://developer.mend.io/api/mc/badges/age/npm/@aws-sdk%2fclient-dynamodb/3.738.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://developer.mend.io/api/mc/badges/adoption/npm/@aws-sdk%2fclient-dynamodb/3.738.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://developer.mend.io/api/mc/badges/compatibility/npm/@aws-sdk%2fclient-dynamodb/3.734.0/3.738.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/npm/@aws-sdk%2fclient-dynamodb/3.734.0/3.738.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
|
[@aws-sdk/client-s3](https://redirect.github.com/aws/aws-sdk-js-v3/tree/main/clients/client-s3)
([source](https://redirect.github.com/aws/aws-sdk-js-v3/tree/HEAD/clients/client-s3))
| [`3.735.0` ->
`3.740.0`](https://renovatebot.com/diffs/npm/@aws-sdk%2fclient-s3/3.735.0/3.740.0)
|
[![age](https://developer.mend.io/api/mc/badges/age/npm/@aws-sdk%2fclient-s3/3.740.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://developer.mend.io/api/mc/badges/adoption/npm/@aws-sdk%2fclient-s3/3.740.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://developer.mend.io/api/mc/badges/compatibility/npm/@aws-sdk%2fclient-s3/3.735.0/3.740.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/npm/@aws-sdk%2fclient-s3/3.735.0/3.740.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
|
[@aws-sdk/client-secrets-manager](https://redirect.github.com/aws/aws-sdk-js-v3/tree/main/clients/client-secrets-manager)
([source](https://redirect.github.com/aws/aws-sdk-js-v3/tree/HEAD/clients/client-secrets-manager))
| [`3.734.0` ->
`3.738.0`](https://renovatebot.com/diffs/npm/@aws-sdk%2fclient-secrets-manager/3.734.0/3.738.0)
|
[![age](https://developer.mend.io/api/mc/badges/age/npm/@aws-sdk%2fclient-secrets-manager/3.738.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://developer.mend.io/api/mc/badges/adoption/npm/@aws-sdk%2fclient-secrets-manager/3.738.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://developer.mend.io/api/mc/badges/compatibility/npm/@aws-sdk%2fclient-secrets-manager/3.734.0/3.738.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/npm/@aws-sdk%2fclient-secrets-manager/3.734.0/3.738.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
|
[@aws-sdk/client-sqs](https://redirect.github.com/aws/aws-sdk-js-v3/tree/main/clients/client-sqs)
([source](https://redirect.github.com/aws/aws-sdk-js-v3/tree/HEAD/clients/client-sqs))
| [`3.734.0` ->
`3.738.0`](https://renovatebot.com/diffs/npm/@aws-sdk%2fclient-sqs/3.734.0/3.738.0)
|
[![age](https://developer.mend.io/api/mc/badges/age/npm/@aws-sdk%2fclient-sqs/3.738.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://developer.mend.io/api/mc/badges/adoption/npm/@aws-sdk%2fclient-sqs/3.738.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://developer.mend.io/api/mc/badges/compatibility/npm/@aws-sdk%2fclient-sqs/3.734.0/3.738.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/npm/@aws-sdk%2fclient-sqs/3.734.0/3.738.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
|
[@aws-sdk/lib-dynamodb](https://redirect.github.com/aws/aws-sdk-js-v3/tree/main/lib/lib-dynamodb)
([source](https://redirect.github.com/aws/aws-sdk-js-v3/tree/HEAD/lib/lib-dynamodb))
| [`3.734.0` ->
`3.738.0`](https://renovatebot.com/diffs/npm/@aws-sdk%2flib-dynamodb/3.734.0/3.738.0)
|
[![age](https://developer.mend.io/api/mc/badges/age/npm/@aws-sdk%2flib-dynamodb/3.738.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://developer.mend.io/api/mc/badges/adoption/npm/@aws-sdk%2flib-dynamodb/3.738.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://developer.mend.io/api/mc/badges/compatibility/npm/@aws-sdk%2flib-dynamodb/3.734.0/3.738.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/npm/@aws-sdk%2flib-dynamodb/3.734.0/3.738.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
|
[@typescript-eslint/eslint-plugin](https://typescript-eslint.io/packages/eslint-plugin)
([source](https://redirect.github.com/typescript-eslint/typescript-eslint/tree/HEAD/packages/eslint-plugin))
| [`8.21.0` ->
`8.22.0`](https://renovatebot.com/diffs/npm/@typescript-eslint%2feslint-plugin/8.21.0/8.22.0)
|
[![age](https://developer.mend.io/api/mc/badges/age/npm/@typescript-eslint%2feslint-plugin/8.22.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://developer.mend.io/api/mc/badges/adoption/npm/@typescript-eslint%2feslint-plugin/8.22.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://developer.mend.io/api/mc/badges/compatibility/npm/@typescript-eslint%2feslint-plugin/8.21.0/8.22.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/npm/@typescript-eslint%2feslint-plugin/8.21.0/8.22.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
|
[@typescript-eslint/parser](https://typescript-eslint.io/packages/parser)
([source](https://redirect.github.com/typescript-eslint/typescript-eslint/tree/HEAD/packages/parser))
| [`8.21.0` ->
`8.22.0`](https://renovatebot.com/diffs/npm/@typescript-eslint%2fparser/8.21.0/8.22.0)
|
[![age](https://developer.mend.io/api/mc/badges/age/npm/@typescript-eslint%2fparser/8.22.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://developer.mend.io/api/mc/badges/adoption/npm/@typescript-eslint%2fparser/8.22.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://developer.mend.io/api/mc/badges/compatibility/npm/@typescript-eslint%2fparser/8.21.0/8.22.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/npm/@typescript-eslint%2fparser/8.21.0/8.22.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
| [electrodb](https://redirect.github.com/tywalch/electrodb) | [`3.0.1`
-> `3.1.0`](https://renovatebot.com/diffs/npm/electrodb/3.0.1/3.1.0) |
[![age](https://developer.mend.io/api/mc/badges/age/npm/electrodb/3.1.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://developer.mend.io/api/mc/badges/adoption/npm/electrodb/3.1.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://developer.mend.io/api/mc/badges/compatibility/npm/electrodb/3.0.1/3.1.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/npm/electrodb/3.0.1/3.1.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
| [lint-staged](https://redirect.github.com/lint-staged/lint-staged) |
[`15.4.2` ->
`15.4.3`](https://renovatebot.com/diffs/npm/lint-staged/15.4.2/15.4.3) |
[![age](https://developer.mend.io/api/mc/badges/age/npm/lint-staged/15.4.3?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://developer.mend.io/api/mc/badges/adoption/npm/lint-staged/15.4.3?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://developer.mend.io/api/mc/badges/compatibility/npm/lint-staged/15.4.2/15.4.3?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/npm/lint-staged/15.4.2/15.4.3?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|

---

### Release Notes

<details>
<summary>aws/aws-sdk-js-v3 (@&#8203;aws-sdk/client-dynamodb)</summary>

###
[`v3.738.0`](https://redirect.github.com/aws/aws-sdk-js-v3/blob/HEAD/clients/client-dynamodb/CHANGELOG.md#37380-2025-01-29)

[Compare
Source](https://redirect.github.com/aws/aws-sdk-js-v3/compare/v3.734.0...v3.738.0)

**Note:** Version bump only for package
[@&#8203;aws-sdk/client-dynamodb](https://redirect.github.com/aws-sdk/client-dynamodb)

</details>

<details>
<summary>aws/aws-sdk-js-v3 (@&#8203;aws-sdk/client-s3)</summary>

###
[`v3.740.0`](https://redirect.github.com/aws/aws-sdk-js-v3/blob/HEAD/clients/client-s3/CHANGELOG.md#37400-2025-01-31)

[Compare
Source](https://redirect.github.com/aws/aws-sdk-js-v3/compare/v3.738.0...v3.740.0)

**Note:** Version bump only for package
[@&#8203;aws-sdk/client-s3](https://redirect.github.com/aws-sdk/client-s3)

###
[`v3.738.0`](https://redirect.github.com/aws/aws-sdk-js-v3/blob/HEAD/clients/client-s3/CHANGELOG.md#37380-2025-01-29)

[Compare
Source](https://redirect.github.com/aws/aws-sdk-js-v3/compare/v3.735.0...v3.738.0)

##### Features

- **client-s3:** Change the type of MpuObjectSize in
CompleteMultipartUploadRequest from int to long.
([c7c525a](https://redirect.github.com/aws/aws-sdk-js-v3/commit/c7c525a07740d92e8c7925a5d0f19931baabb24a))

</details>

<details>
<summary>aws/aws-sdk-js-v3
(@&#8203;aws-sdk/client-secrets-manager)</summary>

###
[`v3.738.0`](https://redirect.github.com/aws/aws-sdk-js-v3/blob/HEAD/clients/client-secrets-manager/CHANGELOG.md#37380-2025-01-29)

[Compare
Source](https://redirect.github.com/aws/aws-sdk-js-v3/compare/v3.734.0...v3.738.0)

**Note:** Version bump only for package
[@&#8203;aws-sdk/client-secrets-manager](https://redirect.github.com/aws-sdk/client-secrets-manager)

</details>

<details>
<summary>aws/aws-sdk-js-v3 (@&#8203;aws-sdk/client-sqs)</summary>

###
[`v3.738.0`](https://redirect.github.com/aws/aws-sdk-js-v3/blob/HEAD/clients/client-sqs/CHANGELOG.md#37380-2025-01-29)

[Compare
Source](https://redirect.github.com/aws/aws-sdk-js-v3/compare/v3.734.0...v3.738.0)

**Note:** Version bump only for package
[@&#8203;aws-sdk/client-sqs](https://redirect.github.com/aws-sdk/client-sqs)

</details>

<details>
<summary>aws/aws-sdk-js-v3 (@&#8203;aws-sdk/lib-dynamodb)</summary>

###
[`v3.738.0`](https://redirect.github.com/aws/aws-sdk-js-v3/blob/HEAD/lib/lib-dynamodb/CHANGELOG.md#37380-2025-01-29)

[Compare
Source](https://redirect.github.com/aws/aws-sdk-js-v3/compare/v3.734.0...v3.738.0)

**Note:** Version bump only for package
[@&#8203;aws-sdk/lib-dynamodb](https://redirect.github.com/aws-sdk/lib-dynamodb)

</details>

<details>
<summary>typescript-eslint/typescript-eslint
(@&#8203;typescript-eslint/eslint-plugin)</summary>

###
[`v8.22.0`](https://redirect.github.com/typescript-eslint/typescript-eslint/blob/HEAD/packages/eslint-plugin/CHANGELOG.md#8220-2025-01-27)

[Compare
Source](https://redirect.github.com/typescript-eslint/typescript-eslint/compare/v8.21.0...v8.22.0)

##### 🩹 Fixes

- **eslint-plugin:** \[no-unnecessary-template-expression] handle
template literal type
([#&#8203;10612](https://redirect.github.com/typescript-eslint/typescript-eslint/pull/10612))
- **eslint-plugin:** \[prefer-readonly] autofixer doesn't add type to
property that is mutated in the constructor
([#&#8203;10552](https://redirect.github.com/typescript-eslint/typescript-eslint/pull/10552))
- **eslint-plugin:** \[no-extraneous-class] handle accessor keyword
([#&#8203;10678](https://redirect.github.com/typescript-eslint/typescript-eslint/pull/10678))
- **eslint-plugin:** \[no-shadow] don't report unnecessarily on valid
ways of using module augmentation
([#&#8203;10616](https://redirect.github.com/typescript-eslint/typescript-eslint/pull/10616))
- **eslint-plugin:** \[no-duplicate-type-constituents] handle nested
types
([#&#8203;10638](https://redirect.github.com/typescript-eslint/typescript-eslint/pull/10638))
- **eslint-plugin:** \[prefer-nullish-coalescing] doesn't report on
ternary but on equivalent ||
([#&#8203;10517](https://redirect.github.com/typescript-eslint/typescript-eslint/pull/10517))

##### ❤️ Thank You

-   mdm317
- Olivier Zalmanski
[@&#8203;OlivierZal](https://redirect.github.com/OlivierZal)
-   Ronen Amiel
-   YeonJuan [@&#8203;yeonjuan](https://redirect.github.com/yeonjuan)

You can read about our [versioning
strategy](https://main--typescript-eslint.netlify.app/users/versioning)
and
[releases](https://main--typescript-eslint.netlify.app/users/releases)
on our website.

</details>

<details>
<summary>typescript-eslint/typescript-eslint
(@&#8203;typescript-eslint/parser)</summary>

###
[`v8.22.0`](https://redirect.github.com/typescript-eslint/typescript-eslint/blob/HEAD/packages/parser/CHANGELOG.md#8220-2025-01-27)

[Compare
Source](https://redirect.github.com/typescript-eslint/typescript-eslint/compare/v8.21.0...v8.22.0)

##### 🚀 Features

- **parser:** add standalone isolatedDeclarations option
([#&#8203;10499](https://redirect.github.com/typescript-eslint/typescript-eslint/pull/10499))

##### ❤️ Thank You

-   Josh Goldberg ✨

You can read about our [versioning
strategy](https://main--typescript-eslint.netlify.app/users/versioning)
and
[releases](https://main--typescript-eslint.netlify.app/users/releases)
on our website.

</details>

<details>
<summary>tywalch/electrodb (electrodb)</summary>

###
[`v3.1.0`](https://redirect.github.com/tywalch/electrodb/blob/HEAD/CHANGELOG.md#310)

[Compare
Source](https://redirect.github.com/tywalch/electrodb/compare/c788e843741a6d0753bc42563bef44a50cbb2842...a1b66277d52fa4dfef1f621166df6fd7397cb44d)

##### Fixed

- [Issue
#&#8203;464](https://redirect.github.com/tywalch/electrodb/issues/464);
When specifing return attributes on retrieval methods, ElectroDB would
unexpectly return null or missing values if the options chosen resulted
in an empty object being returned. This behavor could be confused with
no results being found. ElectroDB now returns the empty object in these
cases.

##### Added

- ElectroDB Error objects no contain a `params()` method. If your
operation resulted in an error thrown by the DynamoDB client, you can
call the `params()` method to get the compiled parameters sent to
DynamoDB. This can be helpful for debugging. Note, that if the error was
thrown prior to parameter creation (validation errors, invalid query
errors, etc) then the `params()` method will return the value `null`.

</details>

<details>
<summary>lint-staged/lint-staged (lint-staged)</summary>

###
[`v15.4.3`](https://redirect.github.com/lint-staged/lint-staged/blob/HEAD/CHANGELOG.md#1543)

[Compare
Source](https://redirect.github.com/lint-staged/lint-staged/compare/v15.4.2...v15.4.3)

##### Patch Changes

-
[#&#8203;1512](https://redirect.github.com/lint-staged/lint-staged/pull/1512)
[`cbfed1d`](https://redirect.github.com/lint-staged/lint-staged/commit/cbfed1dfd2465c4198c692955281f0836600bea1)
Thanks [@&#8203;tarik02](https://redirect.github.com/tarik02)! - Adjust
TypeScript types for the default export so that it can be used as a
value without error TS2693.

</details>

---

### Configuration

📅 **Schedule**: Branch creation - "after 2pm on Saturday" in timezone
Europe/Zurich, Automerge - At any time (no schedule defined).

🚦 **Automerge**: Enabled.

♻ **Rebasing**: Whenever PR is behind base branch, or you tick the
rebase/retry checkbox.

👻 **Immortal**: This PR will be recreated if closed unmerged. Get
[config
help](https://redirect.github.com/renovatebot/renovate/discussions) if
that's undesired.

---

- [ ] <!-- rebase-check -->If you want to rebase/retry this PR, check
this box

---

This PR was generated by [Mend Renovate](https://mend.io/renovate/).
View the [repository job
log](https://developer.mend.io/github/adobe/spacecat-shared).

<!--renovate-debug:eyJjcmVhdGVkSW5WZXIiOiIzOS4xNDUuMCIsInVwZGF0ZWRJblZlciI6IjM5LjE0NS4wIiwidGFyZ2V0QnJhbmNoIjoibWFpbiIsImxhYmVscyI6W119-->

Co-authored-by: renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>